services:
  - type: web
    name: landmass-reservation-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MDB_URI
        sync: false
      - key: NODE_ENV
        value: production